name: MCFriends
main: io.github.scientiist.mcfriends.MCFriends
version: Revision  1
author: Josh MadScientist
commands:
  addfriend:
    permission: mcfriends.add
    default: true
    description: Adds a player as your friend
    usage: "Usage: /<command> <player>"
  tofriend:
    permission: mcfriends.to
    default: true
    description: Teleports to a friend.
    usage: "Usage: /<command> <player>"
  friendconf:
    permission: mcfriends.configure
    default: true
    description: Configure personal settings for Friends
    usage: "Usage: /<command>"