name: MCFriends
main: io.github.scientiist.mcfriends.MCFriends
version: Revision  1
author: Josh MadScientist
commands:
  addfriend:
    permission: mcfriends.add
    default: true
    description: Adds a player as your friend
    usage: "Usage: /<command> <player>"